/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    BarChart: typeof import('./components/BarChart.vue')['default']
    Chart: typeof import('./components/PieChart.vue')['default']
    ChatBot: typeof import('./components/ChatBot.vue')['default']
    Dashboard: typeof import('./components/report.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PieChart: typeof import('./components/PieChart.vue')['default']
    Report: typeof import('./components/report.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNavBar: typeof import('./components/SideNavBar.vue')['default']
  }
}
